version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "django-microservice"
    image: "django-microservice-image"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
