### Access token
POST http://localhost:8000/api/token/
Content-Type: application/json

{
    "username": "shayon",
    "password": "Test1234"
}

### Refresh token
POST http://localhost:8000/api/token/refresh/
Content-Type: application/json

{
    "refresh": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTY5NzQ3MTI3MSwiaWF0IjoxNjg5Njk1MjcxLCJqdGkiOiJjNjljNmZkNmFkNDc0ZGE1OTdmYWYwY2E4OWNjZWJhNiIsInVzZXJfaWQiOjEsInVzZXJuYW1lIjoic2hheW9uIn0.U8A38EGrOMqF8orrnOcEfjTSLJnZKRnDiErB23OV5AU"
}



### Protected route
GET http://localhost:8000/api/protected/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjg5NzExMjE0LCJpYXQiOjE2ODk3MTA5MTQsImp0aSI6IjRhOGU0MTk4MzAyZTQ5NzA5NGQ3MTkxYmYxYTc1MTYzIiwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJzaGF5b24ifQ.ENi_DNKjxLh1zqbpWcFcAsLxQGqSqhu8VD_b_vp0BTA