version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-microservice
    image: flask-microservice-image
    ports:
      - 5000:5000
    volumes:
      - ./:/app
      - /virtual-env
    depends_on:
      - db # this means db container must run first
      - phpmyadmin

  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    env_file:
      - ./.env

    volumes:
      - .dbdata:/var/lib/mysql
      # all files will be reflected here in db data
    ports:
      - 33067:3306
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

