# Generated by Django 3.2.6 on 2021-08-09 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetup',
            name='image',
        ),
    ]
