# Generated by Django 3.2.6 on 2021-08-09 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0002_remove_meetup_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='image',
            field=models.ImageField(default='test', upload_to='uploads'),
            preserve_default=False,
        ),
    ]
