version: '3.9'

services:
  backend_api_ser:
    container_name: admin_con
    image: django_docker_image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - /virtual-env
    depends_on:
      - mysql_admin_db_ser

  mysql_admin_db_ser:
    container_name: mysql_admin_con
    image: mysql:5.7.29
    restart: always
    env_file:
      - ./.env
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306
