version: '3.9'

services:
  backend_api_ser:
    container_name: admin_con
    image: django_docker_image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - /virtual-env
    networks:
      - default
    depends_on:
      - mysql_admin_db_ser
      - rabbitmq_ser

  mysql_admin_db_ser:
    container_name: mysql_admin_con
    image: mysql:5.7.29
    restart: always
    env_file:
      - ./.env
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306
    networks:
      - default

  #  docker run -it --rm --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:3.9-management
  rabbitmq_ser:
    container_name: rabbitmq_con
    image: rabbitmq:3.11.6-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

networks:
  default:
    driver: bridge
