# Generated by Django 2.1.2 on 2018-10-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20181011_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='summary',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
    ]
